<div >
<img src = "../banner.jpg" />
</div>

<a href="https://colab.research.google.com/github/ignaciomsarmiento/BDML_202610/blob/main/Lecture11/01_NN_XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# XOR




q  | p | q v p 
---|---|------|
0 | 0 | 0 |
0 | 1 | 1 |
1 | 0 | 1 |
1 | 1 | 0 |


## Llamando las librerías

In [ ]:
# install.packages("pacman") #run this line if you use Google Colab

In [1]:
require('pacman')
p_load("tidyverse","keras3",'caret')

Loading required package: pacman

## Creamos las variables

In [2]:
X<-matrix(c(0,0,0,1,1,0,1,1),nrow=4,byrow=TRUE)
X

     [,1] [,2]
[1,] 0    0
[2,] 0    1
[3,] 1    0
[4,] 1    1

In [3]:
y<-matrix(c(0,1,1,0),nrow=4,byrow=TRUE)
y

     [,1]
[1,] 0
[2,] 1
[3,] 1
[4,] 0

## Entrenamos la red

In [4]:
model <- keras_model_sequential() 

model %>% 
  layer_dense(units = 16, activation = 'relu', input_shape = c(2)) %>% #activación
  layer_dense(units = 1, activation = 'sigmoid') #output

model %>% compile(
  optimizer = 'adam',
  loss = 'binary_crossentropy',
  metrics = c('binary_accuracy')
)

history <- model %>% fit(
  X, y, 
  epochs = 1000
)

In [5]:
summary(model)

Model: "sequential"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                      ┃ Output Shape             ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                     │ (None, 16)               │            48 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ dense_1 (Dense)                   │ (None, 1)                │            17 │
└───────────────────────────────────┴──────────────────────────┴───────────────┘
 Total params: 197 (792.00 B)
 Trainable params: 65 (260.00 B)
 Non-trainable params: 0 (0.00 B)
 Optimizer params: 132 (532.00 B)

## Resultados

In [6]:
y_hat <- model  %>% predict(X) 
y_hat <- ifelse(y_hat>0.5,1,0)
y_hat

     [,1]
[1,] 0
[2,] 1
[3,] 1
[4,] 0

In [7]:
confusionMatrix(data = factor(as.numeric(y_hat), levels = 0:1), 
  reference = factor(y, levels = 0:1))

Confusion Matrix and Statistics

          Reference
Prediction 0 1
         0 2 0
         1 0 2

               Accuracy : 1
                 95% CI : (0.3976, 1)
    No Information Rate : 0.5
    P-Value [Acc > NIR] : 0.0625

                  Kappa : 1

 Mcnemar's Test P-Value : NA

            Sensitivity : 1.0
            Specificity : 1.0
         Pos Pred Value : 1.0
         Neg Pred Value : 1.0
             Prevalence : 0.5
         Detection Rate : 0.5
   Detection Prevalence : 0.5
      Balanced Accuracy : 1.0

       'Positive' Class : 0